### PR TITLE
fix: stabilization of construction, CI and the use of the lib.

### LINKED ISSUE #58: Invalid gock version?
```shell
$ go get github.com/akamai/AkamaiOPEN-edgegrid-golang
go: finding github.com/h2non/gock v0.0.0-00010101000000-000000000000
go: github.com/h2non/gock@v0.0.0-00010101000000-000000000000: unknown revision 000000000000
go: error loading module requirements
```
I have `go mod` enabled

```shell
$ ls
go.mod
```
`go.mod` file
```
module scratch-space

go 1.12
```

It had worked in the previous version.

https://github.com/akamai/AkamaiOPEN-edgegrid-golang/blob/v0.9.0/go.mod#L14
> 	gopkg.in/h2non/gock.v1 v1.0.15

Changed to 

https://github.com/akamai/AkamaiOPEN-edgegrid-golang/blob/v0.9.1/go.mod#L7
> 	github.com/h2non/gock v0.0.0-00010101000000-000000000000
> ...
> replace github.com/h2non/gock => gopkg.in/h2non/gock.v1 v1.0.14

Clues as to what I'm doing wrong?

There isn't an issue when running it without `go mod` afaik.

### LINKED ISSUE #69: invalid version: unknown revision error on 'h2non/gock' dependency
'go get  ' fails with the error below.

go: github.com/akamai/AkamaiOPEN-edgegrid-golang@v0.9.6 requires
        github.com/h2non/gock@v0.0.0-00010101000000-000000000000: invalid version: unknown revision 000000000000

### PR DESCRIPTION
**Pull request by ldez**
- fix tests. 
- fix travis configuration
    - use only maintained go version.
    - use cache.
    - validate go module files.
    - improve test command.
- fix  gock imports
    - uses `gopkg.in/h2non/gock.v1` instead of `github.com/h2non/gock`

Related to https://github.com/go-acme/lego/issues/1038

Fixes #69
Fixes #58

### CODE REVIEW

**Comment by ldez** [comment]
Friendly ping @martinstibbe @edglynes

**Comment by ldez** [comment]
I rebased the PR, @edglynes could you take a look?

**Comment by tfpereira** [comment]
is there a released version with this PR? I

**Comment by edglynes** [comment]
Not yet. There is presently continuing development. In particular for GTM support. Also open bugs across components. I'd expect a release to be wrapped up in the next week or two.

**Pull request merged**
