### PR TITLE
Fixed several issues with listing enrollments

### PR DESCRIPTION
**Pull request by supernova2468**
https://github.com/akamai/AkamaiOPEN-edgegrid-golang/issues/78

### CODE REVIEW

**Comment by supernova2468** [comment]
Hello? anyone maintaining this repo? @dshafik @njuettner

**Comment by dshafik** [comment]
@supernova2468 sorry, I'm no longer with Akamai, perhaps @javiergarza can help?

**Comment by supernova2468** [comment]
@edglynes ?

**Comment by supernova2468** [comment]
@ellenbluth @javiergarza ?

**Pull request merged**
